### ISSUE TITLE
为什么每次播放都要重新下载字幕

### ISSUE THREAD

**Issue by liuzhebaba** [AssrtOSS/mpv-assrt#1]
这款工具非常好用，但是不知道为什么，我每次重新播放都要重新下载字幕（看到一半退出，然后再次打开）？是哪里需要配置才行么

**Comment by AssrtOpenSource** [comment]
如果不是本地视频，字幕会下载到临时文件夹，导致下次要重新下载。

如果是本地视频，字幕会下载到视频文件同目录下，如果开启了mpv的resume playback，下次可以自动加载。

**Comment by fffonion** [comment]
如果不是本地视频，字幕会下载到临时文件夹，导致下次要重新下载。

如果是本地视频，字幕会下载到视频文件同目录下，如果开启了mpv的resume playback，下次可以自动加载。

**Comment by fffonion** [comment]
因为没有收到回复，本issue将关闭。如果仍有疑问，请重新打开issue

**Comment by acgtyrant** [comment]
我在本地视频看，字幕并没有被下载到视频文件同目录里

**Comment by acgtyrant** [comment]
我错了，有下载，就是因为视频名和字幕名并不一致，从而重新播放视频时并不会自动加载后者。
