### ISSUE TITLE
可否让下载的字幕自动修改为和视频文件一个文件名

### ISSUE THREAD

**Issue by zwb124** [AssrtOSS/mpv-assrt#10]
如题，感谢！

**Comment by fffonion** [comment]
加上了，请更新新版：）

**Comment by zwb124** [comment]
作者威武，nb

**Comment by zwb124** [comment]
额，哥们，我这个是mac系统，是不是就不能自动改文件名了？

**Comment by fffonion** [comment]
@zwb124 啥系统都可以，要不就是bug [doge]

**Comment by zwb124** [comment]
额，好像我的还是不会自己改，有时间辛苦再研究一下吧

**Comment by fffonion** [comment]
@zwb124 确定更新了版本吗
![42BB6C794857E06BF0060C5872ACE4CC](https://user-images.githubusercontent.com/2135445/74838214-2ae67900-535e-11ea-913e-9318730f7b14.jpg)
javascript版是1.0.4，lua版是1.0.6

**Comment by zwb124** [comment]
你跟我说更新后我把文件打包下载然后把两个文件夹里的文件都覆盖了原来的文件，应该没错啊

发自我的iPhone

**Comment by fffonion** [comment]
下载的字幕是怎么样的命名呢？

**Comment by zwb124** [comment]
就是我选择字幕的时候是什么名字，下载下来还是什么名字

发自我的iPhone

**Comment by fffonion** [comment]
试试按照这个步骤https://github.com/AssrtOSS/mpv-assrt#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
添加一个配置文件，然后把auto_rename设成yes

可以先乱填一个`api_token`来测试是否应用到了配置文件

**Comment by zwb124** [comment]
我就是按照这个弄的，明天我再看看，git会有文件更新延迟吗？比如你更新完了我立刻下载还是旧版的？

发自我的iPhone

**Comment by zwb124** [comment]
我发现字幕文件是全英文的就没事，会被修改，但是如果字幕文件是中英文混合的文件名就不会被改了，就会原封不动的下载下来

**Comment by fffonion** [comment]
视频文件名是啥，我来试试

**Comment by zwb124** [comment]
Spider-Man.Far.from.Home.2019.1080p.BluRay.H264.AAC-RARBG.mp4

**Comment by fffonion** [comment]
我这好像没问题
```
   cplayer:  (+) Video --vid=1 (mjpeg 50x50 1.000fps)
   cplayer:      Subs  --sid=1 'Spider-Man.Far.from.Home.2019.1080p.BluRay.H264.AAC-RARBG.人人影视YYeTs.简体&英文.ass' (ass) (external)
   cplayer:      Subs  --sid=2 'Spider-Man.Far.from.Home.2019.1080p.BluRay.H264.AAC-RARBG.chs.eng.srt' (subrip) (external)
   cplayer:      Subs  --sid=3 'Spider-Man.Far.from.Home.2019.1080p.BluRay.H264.AAC-RARBG.人人影视YYeTs.英文.srt' (subrip) (external)
   cplayer:  (+) Subs  --sid=4 'Spider-Man.Far.from.Home.2019.1080p.BluRay.H264.AAC-RARBG.eng.srt' (subrip) (external)
```

有点迷

**Comment by zwb124** [comment]
我的conf好像没启用，我随便输了一个api密钥，还是能正常下载字幕

**Comment by zwb124** [comment]
怎么才能启用呢？

**Comment by zwb124** [comment]
没事了，就这样吧，其它的视频获取字幕后都会自己改，唯独这个视频不会，怪了

**Comment by fffonion** [comment]
那我关issue了厚，有问题可以重新开issue ：）
