### ISSUE TITLE
Windows 10  和 Linux 下使用Ctrl+a没有反应

### ISSUE THREAD

**Issue by nkta3m** [AssrtOSS/mpv-assrt#13]
Windows10，mpv 0.32.0-734-g7831e52238，  openSUSE 15.2 , mpv 0.32.0+git.20200525T015437.b83bdd1d17
input.conf 设置了 ctrl+a script-binding assrt

同样地配置在 mac 没有问题，在windows 和 Linux 下按快捷键没有反应，求助！

Windows报错信息：
cplayer: Can't load unknown script: C:\Users\aqsd\AppData\Roaming/mpv/scripts/win-helper.vbs
   cplayer: Cannot find main.* for any supported scripting backend in: C:\Users\aqsd\AppData\Roaming/mpv/scripts/modules.js
     assrt: Error: Cannot find module file 'AssFormat.js'
     assrt:     at resolve_module_file (@/defaults.js:503)
     assrt:     at require (@/defaults.js:571)
     assrt:     at C:\Users\aqsd\AppData\Roaming/mpv/scripts/assrt.js:13
     assrt:     at run_script (native)
   cplayer: Cannot find main.* for any supported scripting backend in: C:\Users\aqsd\AppData\Roaming/mpv/scripts/modules
     assrt: Could not load javascript C:\Users\aqsd\AppData\Roaming/mpv/scripts/assrt.js
     assrt:
     assrt: stack traceback:
     assrt:     [string "C:\Users\aqsd\AppData\Roaming/mpv/scripts/as..."]:26: in main chunk
     assrt:     [C]: at 0x00dc27c0
     assrt:     [C]: at 0x00dc1120
     assrt: Lua error: [string "C:\Users\aqsd\AppData\Roaming/mpv/scripts/as..."]:26: module 'modules.AssFormat' not found:
     assrt:     no field package.preload['modules.AssFormat']
     assrt:     no file ':\Users\aqsd\AppData\Roaming/mpv/scripts/modules\AssFormat.lua'
     assrt:     no file 'c:\Program Files\mpv\lua\modules\AssFormat.lua'
     assrt:     no file 'c:\Program Files\mpv\lua\modules\AssFormat\init.lua'
     assrt:     no file 'c:\Program Files\mpv\modules\AssFormat.dll'
     assrt:     no file 'c:\Program Files\mpv\loadall.dll'
     assrt:     no file 'c:\Program Files\mpv\modules.dll'
     assrt:     no file 'c:\Program Files\mpv\loadall.dll'

Linux报错信息：
cplayer: Can't load unknown script: /home/aqsd/.config/mpv/scripts/win-helper.vbs
   cplayer: Cannot find main.* for any supported scripting backend in: /home/aqsd/.config/mpv/scripts/modules.js                             
   cplayer: Can't load unknown script: /home/aqsd/.config/mpv/scripts/assrt.js                                                               
   cplayer: Cannot find main.* for any supported scripting backend in: /home/aqsd/.config/mpv/scripts/modules                                
     assrt: 
     assrt: stack traceback:                                                                                                                  
     assrt: 
     assrt: 
     assrt: 
     assrt: Lua error: [string "/home/aqsd/.config/mpv/scripts/assrt.lua"]:26: module 'modules.AssFormat' not found:
     assrt:     no field package.preload['modules.AssFormat']
     assrt:     no file 'home/aqsd/.config/mpv/scripts/modules/AssFormat.lua'
     assrt:     no file '/usr/share/moonjit-2.2.0/modules/AssFormat.lua'
     assrt:     no file '/usr/local/share/lua/5.1/modules/AssFormat.lua'
     assrt:     no file '/usr/local/share/lua/5.1/modules/AssFormat/init.lua'
     assrt:     no file '/usr/share/lua/5.1/modules/AssFormat.lua'
     assrt:     no file '/usr/share/lua/5.1/modules/AssFormat/init.lua'
     assrt:     no file '/usr/local/lib/lua/5.1/modules/AssFormat.so'
     assrt:     no file '/usr/lib64/lua/5.1/modules/AssFormat.so'
     assrt:     no file '/usr/local/lib/lua/5.1/loadall.so'
     assrt:     no file '/usr/local/lib/lua/5.1/modules.so'
     assrt:     no file '/usr/lib64/lua/5.1/modules.so'
     assrt:     no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by nkta3m** [comment]
找到问题了，Mac下能用是因为版本是mpv stable，windows下换成stable就没问题了，但是Linux因为源里最旧的版本也是20200525的，所以依然不能使用，换用问题  #11 提到的0.33版本，提示api错误，依然无法使用，所以现在只能二选一，mpv stable配合master版本，正常使用，如果追新版，就只能放弃这个脚本了

**Comment by fffonion** [comment]
@nkta3m 我看看新版又改了啥。。0.33之后api很不稳定，建议先不要追新版
