### ISSUE TITLE
下载字幕时网页要求验证

### ISSUE THREAD

**Issue by twio142** [AssrtOSS/mpv-assrt#15]
下载下来的srt文件内容如下：

![image](https://user-images.githubusercontent.com/64556708/124029147-1eb00880-d9f5-11eb-978b-bff1212f7f64.png)

**Comment by AssrtOpenSource** [comment]
你好，
如果使用代理，可以尝试关闭代理。这个验证来自cloudflare，到目前我们没有开启任何防护。出现要求验证可能是请求过多或者代理被屏蔽。


twio142 ***@***.***>于2021年7月1日 周四上午4:47写道：

**Comment by twio142** [comment]
谢谢 :)
