### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Jasonsupreme** [AssrtOSS/mpv-assrt#16]
Can't load unknown script: D:/mpv-x86_64-20210725-git-e2109b6/scripts/win-helper.vbs
Cannot find main.* for any supported scripting backend in: D:/mpv-x86_64-20210725-git-e2109b6/scripts/modules.js
Cannot find main.* for any supported scripting backend in: D:/mpv-x86_64-20210725-git-e2109b6/scripts/modules
[assrt2]
[assrt2] stack traceback:
[assrt2]        [string "D:/mpv-x86_64-20210725-git-e2109b6/scripts/as..."]:26: in main chunk
[assrt2]        [C]: at 0x00e84320
[assrt2]        [C]: at 0x00e82d30
[assrt2] Lua error: [string "D:/mpv-x86_64-20210725-git-e2109b6/scripts/as..."]:26: module 'modules.AssFormat' not found:
[assrt2]        no field package.preload['modules.AssFormat']
[assrt2]        no file ':/mpv-x86_64-20210725-git-e2109b6/scripts/modules\AssFormat.lua'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\lua\modules\AssFormat.lua'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\lua\modules\AssFormat\init.lua'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\modules\AssFormat.dll'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\loadall.dll'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\modules.dll'
[assrt2]        no file 'D:\mpv-x86_64-20210725-git-e2109b6\loadall.dll'
[assrt] Error: Cannot find module file 'AssFormat.js'
[assrt]         at resolve_module_file (@/defaults.js:513)
[assrt]         at require (@/defaults.js:581)
[assrt]         at D:/mpv-x86_64-20210725-git-e2109b6/scripts/assrt.js:13
[assrt]         at run_script (native)
[assrt] Could not load javascript D:/mpv-x86_64-20210725-git-e2109b6/scripts/assrt.js

**Comment by fffonion** [comment]
Hi @Jasonsupreme please use this version  https://github.com/AssrtOSS/mpv-assrt/blob/0.33/scripts/assrt.lua, i need to promote it to master. mpv starting 0.33 introduces a breaking change of loading scripts
