### ISSUE TITLE
依赖库不存在了

### ISSUE THREAD

**Issue by IPlayForHer** [AssrtOSS/mpv-assrt#2]
依赖库不存在了，没法使用了

**Comment by fffonion** [comment]
你好，依赖库已经打包在modules.js文件夹中，无需额外下载

**Comment by Mackel123** [comment]
按快捷键，似乎已经没有办法呼出搜索字幕的命令了

**Comment by IPlayForHer** [comment]
所以有解决办法吗


 
---原始邮件---
发件人: "Mackel123"<notifications@github.com>
发送时间: 2019年4月21日(星期日) 下午4:39
收件人: "AssrtOSS/mpv-assrt"<mpv-assrt@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"YouTiao"<youtiao@karpvp.net>;
主题: Re: [AssrtOSS/mpv-assrt] 依赖库不存在了 (#2)



按快捷键，似乎已经没有办法呼出搜索字幕的命令了

**Comment by fffonion** [comment]
@Mackel123  请提供一下mpv的版本，和按快捷键之后控制台的输出信息

**Comment by Mackel123** [comment]
> @Mackel123 请提供一下mpv的版本，和按快捷键之后控制台的输出信息

Information for package mpv:
----------------------------
Repository     : Main Repository (OSS)                     
Name           : mpv                                       
Version        : 0.29.1-28.5                               
Arch           : x86_64                                    
Vendor         : openSUSE                                  
Installed Size : 2.3 MiB                                   
Installed      : Yes                                       
Status         : up-to-date                                
Source package : mpv-0.29.1-28.5.src                       
Summary        : Advanced general-purpose multimedia player
Description    :                                           
    mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety
    of video file formats, audio and video codecs, and subtitle types.

这个是版本，快捷键按了之后没有任何反应

**Comment by fffonion** [comment]
@Mackel123 如果没有错误信息，可能是快捷键绑定冲突了。可以贴一下`input.conf`的内容吗？这个文件在~/.config/mpv底下。

**Comment by Mackel123** [comment]
> @Mackel123 如果没有错误信息，可能是快捷键绑定冲突了。可以贴一下`input.conf`的内容吗？这个文件在~/.config/mpv底下。

我用的是默认的快捷键哦～

**Comment by fffonion** [comment]
@Mackel123 请按照readme中`快捷键`一节添加另一个快捷键测试，如果仍有问题，请另开一个issue讨论。
