### ISSUE TITLE
快捷键无反应

### ISSUE THREAD

**Issue by Mackel123** [AssrtOSS/mpv-assrt#3]
抱歉：昨天的issue我没有表述清晰，现在问题是这样的，
1、如果设置成ctrl+a的话就会显示以下问题，

`[input] Unknown key 'ctrl-a' at /home/makcelsuse/.config/mpv/input.conf:1`

2、快捷键的话，会显示以下问题，

`input] No key binding found for key 'Ctrl+a'`
或
`[input] No key binding found for key 'a'`

mpv的版本号我昨天放过了，是

Information for package mpv:
----------------------------
Repository     : Main Repository (OSS)                     
Name           : mpv                                       
Version        : 0.29.1-28.5                               
Arch           : x86_64                                    
Vendor         : openSUSE                                  
Installed Size : 2.3 MiB                                   
Installed      : Yes                                       
Status         : up-to-date                                
Source package : mpv-0.29.1-28.5.src                       
Summary        : Advanced general-purpose multimedia player
Description    :                                           
    mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety
    of video file formats, audio and video codecs, and subtitle types.

**Comment by AssrtOpenSource** [comment]
感觉是脚本没有被加载。

可以尝试一下按照readme中的步骤，但是添加`a`到key binding吗

**Comment by fffonion** [comment]
感觉是脚本没有被加载。

可以尝试一下按照readme中的步骤，但是添加`a`到key binding吗

**Comment by Mackel123** [comment]
不报错了，但好像仍然没有反应，是如果本地视频内嵌字幕的话，就不会搜索吗？

**Comment by fffonion** [comment]
内嵌字幕是不影响的。我怀疑是opensuse口味的mpv没有编译mujs支持，所以用不了js脚本（因为MuJS是AGPL授权）。
不过保险起见还请你先检查一下`scripts`位置是否正确，请贴一下`find ~/.config/mpv`的输出。
然后请贴一下`strings $(which mpv)|grep -i js_rot2`以及`ldd $(which mpv)`的输出。

**Comment by Mackel123** [comment]
find ~/.config/mpv的输出：

![image](https://user-images.githubusercontent.com/27003282/57062442-b10fd100-6cf2-11e9-9173-736ad82fc740.png)

strings $(which mpv)|grep -i js_rot2

无输出

ldd $(which mpv)的输出：
<        linux-vdso.so.1 (0x00007ffc01c99000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f604fcb7000)
        libXss.so.1 => /usr/lib64/libXss.so.1 (0x00007f604fcb2000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f604fc9d000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f604fc98000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f604fc8b000)
        libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007f604fbf5000)
        libvdpau.so.1 => /usr/lib64/libvdpau.so.1 (0x00007f604fbed000)
        libwayland-egl.so.1 => /usr/lib64/libwayland-egl.so.1 (0x00007f604fbe8000)
        libwayland-client.so.0 => /usr/lib64/libwayland-client.so.0 (0x00007f604fbd6000)
        libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007f604fbc1000)
        libvapoursynth-script.so.0 => /usr/lib64/libvapoursynth-script.so.0 (0x00007f604fbba000)
        libvapoursynth-45.so => /usr/lib64/libvapoursynth-45.so (0x00007f604fad8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f604fad1000)
        libvulkan.so.1 => /usr/lib64/libvulkan.so.1 (0x00007f604fa7c000)
        libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007f604fa28000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f604fa0e000)
        libcaca.so.0 => /usr/lib64/libcaca.so.0 (0x00007f604f942000)
        libavcodec.so.58 => /usr/lib64/libavcodec.so.58 (0x00007f604e5d7000)
        libva.so.2 => /usr/lib64/libva.so.2 (0x00007f604e5b0000)
        libdvdnav.so.4 => /usr/lib64/libdvdnav.so.4 (0x00007f604e599000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f604e578000)
        libdvdread.so.4 => /usr/lib64/libdvdread.so.4 (0x00007f604e558000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f604e543000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f604e3ff000)
        librubberband.so.2 => /usr/lib64/librubberband.so.2 (0x00007f604e3c2000)
        libass.so.9 => /usr/lib64/libass.so.9 (0x00007f604e38d000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f604e2f4000)
        libsmbclient.so.0 => /usr/lib64/libsmbclient.so.0 (0x00007f604e2c9000)
        liblcms2.so.2 => /usr/lib64/liblcms2.so.2 (0x00007f604e26d000)
        libcdio_paranoia.so.2 => /usr/lib64/libcdio_paranoia.so.2 (0x00007f604e263000)
        libcdio_cdda.so.2 => /usr/lib64/libcdio_cdda.so.2 (0x00007f604e257000)
        libcdio.so.18 => /usr/lib64/libcdio.so.18 (0x00007f604e22b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f604e220000)
        libarchive.so.13 => /usr/lib64/libarchive.so.13 (0x00007f604e167000)
        libuchardet.so.0 => /usr/lib64/libuchardet.so.0 (0x00007f604e142000)
        liblua5.1.so.5 => /usr/lib64/liblua5.1.so.5 (0x00007f604e111000)
        libv4l2.so.0 => /usr/lib64/libv4l2.so.0 (0x00007f604e0ff000)
        libva-x11.so.2 => /usr/lib64/libva-x11.so.2 (0x00007f604e0f7000)
        libgbm.so.1 => /usr/lib64/libgbm.so.1 (0x00007f604e0e6000)
        libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f604dfe8000)
        libwayland-cursor.so.0 => /usr/lib64/libwayland-cursor.so.0 (0x00007f604dfde000)
        libxkbcommon.so.0 => /usr/lib64/libxkbcommon.so.0 (0x00007f604df9c000)
        libXv.so.1 => /usr/lib64/libXv.so.1 (0x00007f604df92000)
        libbluray.so.2 => /usr/lib64/libbluray.so.2 (0x00007f604df42000)
        libavutil.so.56 => /usr/lib64/libavutil.so.56 (0x00007f604deca000)
        libavformat.so.58 => /usr/lib64/libavformat.so.58 (0x00007f604dc9b000)
        libswscale.so.5 => /usr/lib64/libswscale.so.5 (0x00007f604dc11000)
        libavfilter.so.7 => /usr/lib64/libavfilter.so.7 (0x00007f604d935000)
        libswresample.so.3 => /usr/lib64/libswresample.so.3 (0x00007f604d914000)
        libva-drm.so.2 => /usr/lib64/libva-drm.so.2 (0x00007f604d90f000)
        libavdevice.so.58 => /usr/lib64/libavdevice.so.58 (0x00007f604d8eb000)
        libva-wayland.so.2 => /usr/lib64/libva-wayland.so.2 (0x00007f604d8e5000)
        libjack.so.0 => /usr/lib64/libjack.so.0 (0x00007f604d89a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f604d6d5000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f604d6a8000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f604d69b000)
        libffi.so.7 => /usr/lib64/libffi.so.7 (0x00007f604d68f000)
        libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007f604d5d2000)
        libpython3.7m.so.1.0 => /usr/lib64/libpython3.7m.so.1.0 (0x00007f604d25a000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f604d0cb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f605002e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f604d0b1000)
        libzimg.so.2 => /usr/lib64/libzimg.so.2 (0x00007f604cff7000)
        libpulsecommon-12.2.so => /usr/lib64/pulseaudio/libpulsecommon-12.2.so (0x00007f604cf70000)
        libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007f604cf1c000)
        libslang.so.2 => /usr/lib64/libslang.so.2 (0x00007f604cc55000)
        libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007f604cc17000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f604cbe5000)
        libvpx.so.6 => /usr/lib64/libvpx.so.6 (0x00007f604c9a0000)
        libwebpmux.so.3 => /usr/lib64/libwebpmux.so.3 (0x00007f604c994000)
        libwebp.so.7 => /usr/lib64/libwebp.so.7 (0x00007f604c925000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f604c8ec000)
        libdav1d.so.1 => /usr/lib64/libdav1d.so.1 (0x00007f604c7d7000)
        libcelt0.so.2 => /usr/lib64/libcelt0.so.2 (0x00007f604c7bc000)
        libzvbi.so.0 => /usr/lib64/libzvbi.so.0 (0x00007f604c72b000)
        libaom.so.0 => /usr/lib64/libaom.so.0 (0x00007f604c22c000)
        libcodec2.so.0.8 => /usr/lib64/libcodec2.so.0.8 (0x00007f604c1c0000)
        libfdk-aac.so.1 => /usr/lib64/libfdk-aac.so.1 (0x00007f604c0ff000)
        libgsm.so.1 => /usr/lib64/libgsm.so.1 (0x00007f604c0f0000)
        libmp3lame.so.0 => /usr/lib64/libmp3lame.so.0 (0x00007f604c075000)
        libopenjp2.so.7 => /usr/lib64/libopenjp2.so.7 (0x00007f604c022000)
        libopus.so.0 => /usr/lib64/libopus.so.0 (0x00007f604bfc2000)
        libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007f604bfa5000)
        libSvtAv1Enc.so.suse0 => /usr/lib64/libSvtAv1Enc.so.suse0 (0x00007f604ba78000)
        libtheoraenc.so.1 => /usr/lib64/libtheoraenc.so.1 (0x00007f604ba3c000)
        libtheoradec.so.1 => /usr/lib64/libtheoradec.so.1 (0x00007f604ba1f000)
        libtwolame.so.0 => /usr/lib64/libtwolame.so.0 (0x00007f604b9fa000)
        libvo-amrwbenc.so.0 => /usr/lib64/libvo-amrwbenc.so.0 (0x00007f604b9de000)
        libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007f604b9af000)
        libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007f604b902000)
        libx264.so.155 => /usr/lib64/libx264.so.155 (0x00007f604b65b000)
        libx265.so.169 => /usr/lib64/libx265.so.169 (0x00007f604a6fa000)
        libxvidcore.so.4 => /usr/lib64/libxvidcore.so.4 (0x00007f604a5e6000)
        libsamplerate.so.0 => /usr/lib64/libsamplerate.so.0 (0x00007f604a478000)
        libfftw3.so.3 => /usr/lib64/libfftw3.so.3 (0x00007f604a26d000)
        libfribidi.so.0 => /usr/lib64/libfribidi.so.0 (0x00007f604a24f000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f604a208000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f604a14d000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f604a049000)
        libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007f604a015000)
        libndr.so.0 => /usr/lib64/libndr.so.0 (0x00007f6049ff8000)
        liblibsmb-samba4.so => /usr/lib64/samba/liblibsmb-samba4.so (0x00007f6049f82000)
        liblibcli-lsa3-samba4.so => /usr/lib64/samba/liblibcli-lsa3-samba4.so (0x00007f6049f7b000)
        libsamba-security-samba4.so => /usr/lib64/samba/libsamba-security-samba4.so (0x00007f6049f58000)
        libmsrpc3-samba4.so => /usr/lib64/samba/libmsrpc3-samba4.so (0x00007f6049f33000)
        libsmbconf.so.0 => /usr/lib64/libsmbconf.so.0 (0x00007f6049ea6000)
        libsamba-util.so.0 => /usr/lib64/libsamba-util.so.0 (0x00007f6049e28000)
        libreplace-samba4.so => /usr/lib64/samba/libreplace-samba4.so (0x00007f6049e23000)
        libsamba-errors.so.1 => /usr/lib64/libsamba-errors.so.1 (0x00007f6049cd7000)
        libtevent-util.so.0 => /usr/lib64/libtevent-util.so.0 (0x00007f6049cd0000)
        libutil-cmdline-samba4.so => /usr/lib64/samba/libutil-cmdline-samba4.so (0x00007f6049cca000)
        libgse-samba4.so => /usr/lib64/samba/libgse-samba4.so (0x00007f6049c9e000)
        libcli-smb-common-samba4.so => /usr/lib64/samba/libcli-smb-common-samba4.so (0x00007f6049c6a000)
        libdcerpc-samba-samba4.so => /usr/lib64/samba/libdcerpc-samba-samba4.so (0x00007f6049ad4000)
        libndr-standard.so.0 => /usr/lib64/libndr-standard.so.0 (0x00007f60497b5000)
        libsamba3-util-samba4.so => /usr/lib64/samba/libsamba3-util-samba4.so (0x00007f60497a7000)
        libsamba-debug-samba4.so => /usr/lib64/samba/libsamba-debug-samba4.so (0x00007f604979e000)
        libsecrets3-samba4.so => /usr/lib64/samba/libsecrets3-samba4.so (0x00007f6049782000)
        libtevent.so.0 => /usr/lib64/libtevent.so.0 (0x00007f604976b000)
        libtalloc.so.2 => /usr/lib64/libtalloc.so.2 (0x00007f6049755000)
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007f60494c9000)
        libacl.so.1 => /usr/lib64/libacl.so.1 (0x00007f60494be000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f604949e000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f6049332000)
        libv4lconvert.so.0 => /usr/lib64/libv4lconvert.so.0 (0x00007f60492b5000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f60492ad000)
        libwayland-server.so.0 => /usr/lib64/libwayland-server.so.0 (0x00007f6049298000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f6049254000)
        libopenmpt.so.0 => /usr/lib64/libopenmpt.so.0 (0x00007f6049062000)
        libgnutls.so.30 => /usr/lib64/libgnutls.so.30 (0x00007f6048eae000)
        librtmp.so.1 => /usr/lib64/librtmp.so.1 (0x00007f6048e8e000)
        libsrt.so.1 => /usr/lib64/libsrt.so.1 (0x00007f6048e11000)
        libssh.so.4 => /usr/lib64/libssh.so.4 (0x00007f6048d8f000)
        libpostproc.so.55 => /usr/lib64/libpostproc.so.55 (0x00007f6048d75000)
        libavresample.so.4 => /usr/lib64/libavresample.so.4 (0x00007f6048d52000)
        libbs2b.so.0 => /usr/lib64/libbs2b.so.0 (0x00007f6048d4a000)
        liblilv-0.so.0 => /usr/lib64/liblilv-0.so.0 (0x00007f6048d30000)
        libmysofa.so.0 => /usr/lib64/libmysofa.so.0 (0x00007f6048d1f000)
        libvidstab.so.1.1 => /usr/lib64/libvidstab.so.1.1 (0x00007f6048d0a000)
        libzmq.so.5 => /usr/lib64/libzmq.so.5 (0x00007f6048c6d000)
        libsoxr.so.0 => /usr/lib64/libsoxr.so.0 (0x00007f6048c00000)
        libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007f6048bfb000)
        libxcb-shape.so.0 => /usr/lib64/libxcb-shape.so.0 (0x00007f6048bf5000)
        libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007f6048beb000)
        libdc1394.so.22 => /usr/lib64/libdc1394.so.22 (0x00007f6048b72000)
        libSDL2-2.0.so.0 => /usr/lib64/libSDL2-2.0.so.0 (0x00007f6048a2b000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f6048a24000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f6048a1f000)
        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f6048966000)
        libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007f60488e6000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f60488a5000)
        libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007f604889a000)
        libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007f604888b000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f6048882000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f604875e000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f6048739000)
        libgenrand-samba4.so => /usr/lib64/samba/libgenrand-samba4.so (0x00007f6048732000)
        libasn1util-samba4.so => /usr/lib64/samba/libasn1util-samba4.so (0x00007f6048729000)
        libCHARSET3-samba4.so => /usr/lib64/samba/libCHARSET3-samba4.so (0x00007f6048724000)
        libgensec-samba4.so => /usr/lib64/samba/libgensec-samba4.so (0x00007f60486f4000)
        libcli-cldap-samba4.so => /usr/lib64/samba/libcli-cldap-samba4.so (0x00007f60486ea000)
        libcliauth-samba4.so => /usr/lib64/samba/libcliauth-samba4.so (0x00007f60486d3000)
        libsmb-transport-samba4.so => /usr/lib64/samba/libsmb-transport-samba4.so (0x00007f60486c9000)
        libndr-nbt.so.0 => /usr/lib64/libndr-nbt.so.0 (0x00007f60486b1000)
        libsamba-credentials.so.0 => /usr/lib64/libsamba-credentials.so.0 (0x00007f604869a000)
        libsamba-hostconfig.so.0 => /usr/lib64/libsamba-hostconfig.so.0 (0x00007f604866b000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f6048665000)
        libdcerpc-binding.so.0 => /usr/lib64/libdcerpc-binding.so.0 (0x00007f604863f000)
        libdbwrap-samba4.so => /usr/lib64/samba/libdbwrap-samba4.so (0x00007f6048631000)
        libndr-samba-samba4.so => /usr/lib64/samba/libndr-samba-samba4.so (0x00007f60484f8000)
        libsamba-sockets-samba4.so => /usr/lib64/samba/libsamba-sockets-samba4.so (0x00007f60484dc000)
        libutil-tdb-samba4.so => /usr/lib64/samba/libutil-tdb-samba4.so (0x00007f60484d6000)
        libsocket-blocking-samba4.so => /usr/lib64/samba/libsocket-blocking-samba4.so (0x00007f60484d1000)
        libutil-reg-samba4.so => /usr/lib64/samba/libutil-reg-samba4.so (0x00007f60484ca000)
        libtalloc-report-samba4.so => /usr/lib64/samba/libtalloc-report-samba4.so (0x00007f60484c5000)
        libmessages-util-samba4.so => /usr/lib64/samba/libmessages-util-samba4.so (0x00007f60484c0000)
        libsys-rw-samba4.so => /usr/lib64/samba/libsys-rw-samba4.so (0x00007f60484bb000)
        libserver-id-db-samba4.so => /usr/lib64/samba/libserver-id-db-samba4.so (0x00007f60484b5000)
        libiov-buf-samba4.so => /usr/lib64/samba/libiov-buf-samba4.so (0x00007f60484ae000)
        libmessages-dgm-samba4.so => /usr/lib64/samba/libmessages-dgm-samba4.so (0x00007f60484a0000)
        libinterfaces-samba4.so => /usr/lib64/samba/libinterfaces-samba4.so (0x00007f604849b000)
        libsmbd-shim-samba4.so => /usr/lib64/samba/libsmbd-shim-samba4.so (0x00007f6048496000)
        libsamba-cluster-support-samba4.so => /usr/lib64/samba/libsamba-cluster-support-samba4.so (0x00007f604847e000)
        libtdb-wrap-samba4.so => /usr/lib64/samba/libtdb-wrap-samba4.so (0x00007f6048479000)
        libutil-setid-samba4.so => /usr/lib64/samba/libutil-setid-samba4.so (0x00007f6048472000)
        libtime-basic-samba4.so => /usr/lib64/samba/libtime-basic-samba4.so (0x00007f604846d000)
        libserver-role-samba4.so => /usr/lib64/samba/libserver-role-samba4.so (0x00007f6048468000)
        libldap_r-2.4.so.2 => /usr/lib64/libldap_r-2.4.so.2 (0x00007f6048412000)
        libtdb.so.1 => /usr/lib64/libtdb.so.1 (0x00007f60483f9000)
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f60483e8000)
        libnsl.so.2 => /usr/lib64/libnsl.so.2 (0x00007f60483cb000)
        libkrb5samba-samba4.so => /usr/lib64/samba/libkrb5samba-samba4.so (0x00007f60483bb000)
        libaddns-samba4.so => /usr/lib64/samba/libaddns-samba4.so (0x00007f60483ad000)
        libauthkrb5-samba4.so => /usr/lib64/samba/libauthkrb5-samba4.so (0x00007f6048394000)
        libcli-nbt-samba4.so => /usr/lib64/samba/libcli-nbt-samba4.so (0x00007f6048387000)
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f60482a3000)
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f6048255000)
        libmpg123.so.0 => /usr/lib64/libmpg123.so.0 (0x00007f60481f5000)
        libvorbisfile.so.3 => /usr/lib64/libvorbisfile.so.3 (0x00007f60481eb000)
        libp11-kit.so.0 => /usr/lib64/libp11-kit.so.0 (0x00007f60480b8000)
        libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007f6048099000)
        libunistring.so.2 => /usr/lib64/libunistring.so.2 (0x00007f6047f15000)
        libtasn1.so.6 => /usr/lib64/libtasn1.so.6 (0x00007f6047f01000)
        libnettle.so.6 => /usr/lib64/libnettle.so.6 (0x00007f6047ec6000)
        libhogweed.so.4 => /usr/lib64/libhogweed.so.4 (0x00007f6047e8c000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f6047df2000)
        libserd-0.so.0 => /usr/lib64/libserd-0.so.0 (0x00007f6047dd1000)
        libsord-0.so.0 => /usr/lib64/libsord-0.so.0 (0x00007f6047dc5000)
        libsratom-0.so.0 => /usr/lib64/libsratom-0.so.0 (0x00007f6047db9000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f6047d87000)
        libunwind.so.8 => /usr/lib64/libunwind.so.8 (0x00007f6047d69000)
        libsodium.so.23 => /usr/lib64/libsodium.so.23 (0x00007f6047d11000)
        libpgm-5.2.so.0 => /usr/lib64/libpgm-5.2.so.0 (0x00007f6047cc2000)
        libraw1394.so.11 => /usr/lib64/libraw1394.so.11 (0x00007f6047cb3000)
        libusb-1.0.so.0 => /usr/lib64/libusb-1.0.so.0 (0x00007f6047c97000)
        liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f6047c75000)
        libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f6047c6e000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f6047c42000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f6047b22000)
        libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007f6047ae4000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f6047a54000)
        libsamba-modules-samba4.so => /usr/lib64/samba/libsamba-modules-samba4.so (0x00007f6047a4d000)
        libwbclient.so.0 => /usr/lib64/libwbclient.so.0 (0x00007f6047a3b000)
        libsamdb.so.0 => /usr/lib64/libsamdb.so.0 (0x00007f6047a1f000)
        libcommon-auth-samba4.so => /usr/lib64/samba/libcommon-auth-samba4.so (0x00007f6047a10000)
        libcli-ldap-common-samba4.so => /usr/lib64/samba/libcli-ldap-common-samba4.so (0x00007f6047a06000)
        libldb.so.1 => /usr/lib64/libldb.so.1 (0x00007f60479d0000)
        libldbsamba-samba4.so => /usr/lib64/samba/libldbsamba-samba4.so (0x00007f60479a0000)
        libsamdb-common-samba4.so => /usr/lib64/samba/libsamdb-common-samba4.so (0x00007f604796e000)
        libmsghdr-samba4.so => /usr/lib64/samba/libmsghdr-samba4.so (0x00007f6047967000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f604794e000)
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f604792f000)
        libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f60478c1000)
        libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007f604788c000)
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f604786e000)
        libclidns-samba4.so => /usr/lib64/samba/libclidns-samba4.so (0x00007f6047864000)
        libndr-krb5pac.so.0 => /usr/lib64/libndr-krb5pac.so.0 (0x00007f6047853000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f6047843000)
        libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f604783d000)
        libudev.so.1 => /usr/lib64/libudev.so.1 (0x00007f604780d000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f60477e9000)
        libwinbind-client-samba4.so => /usr/lib64/samba/libwinbind-client-samba4.so (0x00007f60477e3000)
        libMESSAGING-SEND-samba4.so => /usr/lib64/samba/libMESSAGING-SEND-samba4.so (0x00007f60477de000)
        libjansson.so.4 => /usr/lib64/libjansson.so.4 (0x00007f60477cf000)
        libflag-mapping-samba4.so => /usr/lib64/samba/libflag-mapping-samba4.so (0x00007f60477c8000)
>

**Comment by Mackel123** [comment]
solus上测试了一下也没有反应

**Comment by Mackel123** [comment]
在windows下也测试后，发现还是没有反应，是不是脚本出了问题？

**Comment by fffonion** [comment]
脚本位置没问题，但是mpv没有mujs的符号，也没有链接mujs的库，说明的确没有编译javascript支持。
对你后来提到的两个系统，可以用同样的方法用strings和ldd测试是否有js支持。windows版是静态编译的，所以只看strings就可以(可以把exe拷贝到任意linux系统或者用windows自带的linux子系统)。

**Comment by fffonion** [comment]
不好意思，`js_rot2`可能会被strip掉，能否重新测试一下`strings $(which mpv)|grep compile_js`。另外，`strings $(which mpv)|grep "waf configure"`应该可以看到编译选项，如果没有`--enable-javascript`则说明没有启用javascript。

windows版的mpv我记得都是开启javascript的，可以检查一下是否是scripts目录路径问题？

**Comment by Mackel123** [comment]
的确没有--enable-javascript

windows我是直接放到mpv.exe文件同一目录了，用的是scoop仓库里的版本

**Comment by fffonion** [comment]
我刚写了Lua版，可以下载试试，在非windows平台上和js版的功能一致。

windows版本如果是cygwin/msys32编译的可能选到其他的主目录，测试方法是建一个mpv.conf填一些配置看是否生效。或者可以试一下https://mpv.io/installation/ 这里编译的二进制版本。

**Comment by Mackel123** [comment]
非常感谢，我现在马上试试看

**Comment by Mackel123** [comment]
![image](https://user-images.githubusercontent.com/27003282/57122091-05c45200-6dae-11e9-99e7-1c96f5ce929c.png)

加载成功了吧～这个是，我在把快捷键写进默认etc/mpv那里
这个点击还是没有反应～

**Comment by fffonion** [comment]
~加个`a script-binding assrt`到配置里，快捷键可能有冲突~
虽然不是很懂为什么，但是可以试一下把assrt.lua最后的`add_key_binding`改成`add_forced_key_binding`

**Comment by Mackel123** [comment]
好的～

**Comment by Mackel123** [comment]
成功搞定了，但是API似乎有点问题，这个需要在哪里修改啊～是因为射手网已经倒了的原因吗？

[assrt] API failed with code: 30002, message: search engine is unavailable

**Comment by fffonion** [comment]
文件名里有括号没关上，所以挂了，现在修好了：）可以下载最新的脚本

**Comment by Mackel123** [comment]
好的，感谢

**Comment by Mackel123** [comment]
感谢运行正常

**Comment by acgtyrant** [comment]
Close it!

**Comment by fffonion** [comment]
问题已解决，关闭issue
