### ISSUE TITLE
Windows下配置文件放在当前目录下时 a 快捷键失效

### ISSUE THREAD

**Issue by tuchit** [AssrtOSS/mpv-assrt#5]
mpv.conf 在roaming目录时一切正常工作

当我将mpv完全绿色化的时候(也就是将 mpv.conf 放在主目录下的 **portable_config** 目录)
此时快捷键 **a** 无效

同样的纯绿色版下修改input配置的快捷方式也无效

**Comment by fffonion** [comment]
scripts有拷贝到portable_config下吗？

**Comment by tuchit** [comment]
嗯,可以了
