### ISSUE TITLE
使用lua脚本时候，assrt.conf无效

### ISSUE THREAD

**Issue by xiaoleichen** [AssrtOSS/mpv-assrt#6]
而且当MPV同时支持js和lua的时候好像并不是优先使用js，不同系统有不同选择。没发现规律，好像挺随机的。
当使用lua的时候assrt.conf里面的设置没有调用。如果删掉lua脚本，强制使用js的时候conf就有效了。

**Comment by AssrtOpenSource** [comment]
感谢反馈！lua版本没有调用assrt.conf的时候是使用什么系统？

**Comment by xiaoleichen** [comment]
跟系统没关系。
lua版不调用conf在windows和mac下都是这样。
是否优先使用js不知道跟系统有关系没。我有两台mac，一台优先用js，一台优先用了lua。一台windows也是优先用了lua。但是把lua删掉打开mpv让它用js，然后再放回去又优先使用js了。

**Comment by xiaoleichen** [comment]
找了台linux (fedora 31)试了下。
也是优先使用了lua，并且无视了conf。用js就没问题。
另外MPV都是0.30.0版，同时支持js和lua

**Comment by AssrtOpenSource** [comment]
嗯我看mpv的代码里是通过`readdir`来列举scripts文件夹，所以的确是不保证顺序的。我去改一下readme。

我看看lua不加载conf是什么问题。。

**Comment by fffonion** [comment]
修好了，试一下新版吧：）

**Comment by xiaoleichen** [comment]
确认已经修复了。
js和lua都可以用。
谢谢！
