### ISSUE TITLE
不能搜索带有 [ ] 中括号的视频字幕

### ISSUE THREAD

**Issue by tuchit** [AssrtOSS/mpv-assrt#7]
麻烦添加支持对忽略  [ ] 的字幕搜索

比如 Joker 2019_[aaaabbb].mp4
这样的视频无法搜索字幕

**Comment by fffonion** [comment]
@tuchit 暂时不支持非标准的命名方式哦，可以重命名视频文件或者到网站手动下载 https://assrt.net/

**Comment by tuchit** [comment]
没办法实现该功能吗？比如直接用正则表达式忽略中括号内的内容，原理上应该不难实现吧

因为我有时候要做种，改名之后就无法做种了，手动下载的话多少又有点麻烦

**Comment by fffonion** [comment]
多发几个样本来，我看看是什么规律。

道理是这个道理，但是需要考虑各种其他的模式，简单的正则不太好解决的。

**Comment by tuchit** [comment]
比如
the.untouchable.2015.720p.bluray.x264-[Baidu.com].mp4

**Comment by fffonion** [comment]
ojbk 👍 这个可搞

**Comment by tuchit** [comment]
静候佳音

**Comment by fffonion** [comment]
@tuchit 已更新，请尝试重新搜索 =）

**Comment by tuchit** [comment]
还没上传吧，我刚才用total commander一一比较文件了，跟去年的完全一样没变化啊

**Comment by fffonion** [comment]
这是后台的更改，脚本不需要更新

**Comment by tuchit** [comment]
嗯，试了，可行
感谢

**Comment by fffonion** [comment]
关闭issue，如有问题可reopen
