### ISSUE TITLE
可以搜索到，无法下载

### ISSUE THREAD

**Issue by Leerivial** [AssrtOSS/mpv-assrt#8]
Windows版的MPV。

按“a“可以搜索到字幕，选择之后提示“字幕下载失败，请检查控制台输出”。

不知道如何检查控制台输出。

**Comment by fffonion** [comment]
运行`mpv.com`，或者在打开方式里选择`mpv.com`而不是`mpv.exe`就可以看到控制台

**Comment by fffonion** [comment]
修正了一个Lua版本临时目录的问题，可以试试新版

**Comment by fffonion** [comment]
关闭不活跃issue，如有问题请发新帖：）
