### ISSUE TITLE
快捷呼出後顯示搜索字幕

### ISSUE THREAD

**Issue by Mackel123** [AssrtOSS/mpv-assrt#9]
無輸出結果，無論是否有搜索到均無輸出結果，如果一直保持開啓而播放其他視頻也無法繼續搜索。
opensuse tumbleweed

Information for package mpv:
----------------------------
Repository     : Main Repository (OSS)                            
Name           : mpv                                              
Version        : 0.32.0+git.20200208T095058.6799f8e0e9-1.1        
Arch           : x86_64                                           
Vendor         : openSUSE                                         
Installed Size : 2.3 MiB                                          
Installed      : Yes                                              
Status         : up-to-date                                       
Source package : mpv-0.32.0+git.20200208T095058.6799f8e0e9-1.1.src
Summary        : Advanced general-purpose multimedia player   

是否是因爲未搜索到結果所以自動不再顯示了，而且不再進行搜索了？

**Comment by fffonion** [comment]
控制台assrt开头的日志可以贴一下吗

**Comment by Mackel123** [comment]
稍等

**Comment by Mackel123** [comment]
啊，可能是网络原因没有搜到，所以有点打扰了抱歉，不过貌似有一条有关的提示是：
`Can't load unknown script: /home/macksusel/.config/mpv/scripts/win-helper.vbs`

**Comment by fffonion** [comment]
这条可以忽略，这是一个帮助脚本，mpv本身就加载不了，没事

**Comment by Mackel123** [comment]
好的，感谢。
